services:
  - type: web
    name: proshno-potro-api
    runtime: python
    buildCommand: pip install -r requirements.txt && playwright install --with-deps chromium
    startCommand: playwright install chromium && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: proshno-potro
      - key: COLLECTION_NAME
        value: mcq
